apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: open5gs
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |
    logger:
    {{ toYaml .Values.nssf.logger | indent 2 }}

    {{- if .Values.nssf.parameter }}
    parameter:
    {{ toYaml .Values.nssf.parameter | indent 2 }}
    {{- end }}

    #
    nssf:
      sbi:
        dev: net1
        port: 7777
      nsi:
        {{- range .Values.nssf.nsi }}
        - name: "open5gs-nrf-svc-pool"
          port: 7777
          s_nssai:
            {{- toYaml . | nindent 12 }}
        {{- end }}
    nrf:
      sbi:
        - name: "open5gs-nrf-svc-pool"
          port: 7777
