apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-pcf-deployment
  labels:
    epc-mode: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: pcf
  template:
    metadata:
      annotations:
        route53-service-name: '[
                                  { "name": "n.pcf.open5gs.service", "multus-int": "ipvlan-multus-sub-1-cp" }
                               ]'
        k8s.v1.cni.cncf.io/networks: '[ { "name": "ipvlan-multus-sub-1-cp", "interface": "net1" }
                                      ]'      
      labels:
        epc-mode: pcf
    spec:
      nodeSelector:
        nodegroup: Pcf
      initContainers:
        - name: init-pcf
          image: alpine:latest
          command: ['sh', '-c']     
          args:
            - apk update; apk add nmap-ncat; sleep 15;
              until nslookup n.amf.open5gs.service >> /dev/null; do echo waiting for amf to be ready; sleep 5; done;
              until nslookup s5.smf.open5gs.service >> /dev/null; do echo waiting for smf DNS record to be ready;done;
      containers:
        - name: pcf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - sleep 10;
              open5gs-pcfd -c /open5gs/config-map/pcf.yaml
          env:
            - name: DB_URI
              value: {{ .Values.mongo.uri }}
          volumeMounts:
            - name: open5gs-pcf-config
              mountPath: /open5gs/config-map/pcf.yaml
              subPath: "pcf.yaml"
            - mountPath: "/root/"
              name: mongo-ca-cert
              readOnly: true

      volumes:
        - name: open5gs-pcf-config
          configMap:
            name: open5gs-pcf-config
        - name: mongo-ca-cert
          secret:
            secretName: {{ .Values.mongo.caSecretName }}

