{{- if .Values.pcf.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  namespace: open5gs
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    logger:
    {{ toYaml .Values.pcf.logger | indent 2 }}
    {{- if .Values.pcf.parameter }}
    parameter:
    {{ toYaml .Values.pcf.parameter | indent 2 }}
    {{- end }}

    pcf:
      sbi:
        dev: net1
        port: 7777

    nrf:
      sbi:
        - name: "open5gs-nrf-svc-pool"
          port: 7777
{{- end }}
